### PR TITLE
Update freshrss to master 1.6.1

### PR DESCRIPTION
**Pull request by KillianKemps**
Hello,

I found your repository through FreshRSS's official Github which was using your Docker image: https://github.com/FreshRSS/docker-freshrss-production
As the FreshRSS was a little bit outdated, I changed it to point to the last master version 1.6.1

Thanks for having written the Dockerfile!

### CODE REVIEW

**Comment by kokaz** [comment]
Thanks @KillianKemps for your contribution, merging in!

**Comment by KillianKemps** [comment]
You're welcome!

I see that the Docker build is failing on the Docker hub because the `beta` folder has been changed to `master` : https://hub.docker.com/r/kokaz/freshrss/builds/b24rufeudg76ai8nb4jlflw/

Is there something else to do to fix that?

**Comment by kokaz** [comment]
@KillianKemps It was some hard coded settings in Docker Hub, I changed some things so that it will build :) let me know

**Comment by KillianKemps** [comment]
Yes, the build works!

Great, thank you!

**Pull request merged**
